#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┳┏┳┓┏┳┓┓┏
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┃┫ ┃ ┃  ┃ ┗┫
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┛┻ ┻  ┻ ┗┛
#                                


# Core Colors
background            #101418
foreground            #e0e2e8
selection_foreground  #9bcbfb
selection_background  #003353
cursor                #9bcbfb
cursor_text_color     #101418

# Regular Colors
color0  #101418               
color1  #ffb4ab                 
color2  #9bcbfb               
color3  #d3bfe6              
color4  #cee5ff  
color5  #d5e4f7
color6  #b9c8da             
color7  #e0e2e8            

# Bright Colors
color8  #36393e         
color9  #ffb4ab                  
color10 #9bcbfb                
color11 #d3bfe6               
color12 #cee5ff   
color13 #d5e4f7 
color14 #b9c8da              
color15 #e0e2e8             