-- Hyprland Lua config (converted from hyprland.conf).
-- Docs: https://wiki.hypr.land/Configuring/Start/
--
-- NOTE: hyprland.conf is kept as-is. If hyprland.lua exists it is loaded
-- INSTEAD of hyprland.conf, so to fall back just rename/remove this file.

-- Colors are generated by matugen -> ~/.config/hypr/colors.lua
local colors = require("colors")


------------------
---- MONITORS ----
------------------

-- Original had two monitor lines; the later one set scale = 1, which wins.
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "1",
})


---------------------
---- MY PROGRAMS ----
---------------------

local terminal    = "kitty"
local fileManager = "dolphin"
local menu        = "qs ipc call launcherWindow toggle"
local mainMod     = "SUPER"


-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("kdeconnectd")
    hl.exec_cmd("kdeconnect-indicator")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("qs")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- Duplicate env lines from the original conf were de-duplicated.
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_STYLE_OVERRIDE", "Kvantum")
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "0")
hl.env("QT_SCALE_FACTOR", "1")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("GDK_SCALE", "1")
hl.env("GDK_DPI_SCALE", "1")
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GL_VRR_ALLOWED", "0")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("GBM_BACKEND", "nvidia-drm")
hl.env("NVD_BACKEND", "direct")


-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
    general = {
        gaps_in     = 5,
        gaps_out    = 20,
        border_size = 2,

        col = {
            active_border   = { colors = { colors.primary, colors.tertiary },          angle = 45 },
            inactive_border = { colors = { colors.surface_container, colors.outline },  angle = 45 },
        },

        resize_on_border = true,
        layout           = "scrolling",
    },

    scrolling = {
        fullscreen_on_one_column = true,
        column_width             = 0.90,
        follow_focus             = true,
        focus_fit_method         = 1,
        explicit_column_widths   = ".75, .75, .75, .75",
    },

    decoration = {
        rounding       = 35,
        rounding_power = 2,

        active_opacity     = 0.65,
        inactive_opacity   = 0.55,
        fullscreen_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 18,
            render_power = 5,
            color        = colors.shadow,
        },

        blur = {
            enabled           = true,
            size              = 12,
            passes            = 4,
            ignore_opacity    = true,
            new_optimizations = true,
        },
    },

    animations = {
        enabled = true,
    },

    master = {
        new_status = "master",
    },

    misc = {
        force_default_wallpaper = -1,
        disable_hyprland_logo   = true,
    },

    input = {
        kb_layout    = "us",
        kb_variant   = "",
        kb_model     = "",
        kb_options   = "",
        kb_rules     = "",
        left_handed  = true,
        follow_mouse = 1,
        sensitivity  = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },

    gestures = {
        workspace_swipe_invert   = false,
        workspace_swipe_distance = 700,
    },

    group = {
        auto_group           = true,
        insert_after_current = true,

        groupbar = {
            enabled   = true,
            gradients = true,
        },
    },
})


----------------
---- CURVES ----
----------------

hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1} } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1} } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1} } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1.0} } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1} } })
hl.curve("bounceCurve",    { type = "bezier", points = { {0.6, 1.5},   {0.8, 1} } })

hl.animation({ leaf = "global",        enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true, speed = 4.79, bezier = "bounceCurve" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 4.5,  bezier = "bounceCurve", style = "slide 10%" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 4.5,  bezier = "linear",      style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 0.5,  bezier = "bounceCurve",  style = "slidefadevert" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 4.5,  bezier = "bounceCurve",  style = "slidefadevert" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 4.5,  bezier = "bounceCurve",  style = "slidefadevert" })


----------------
---- DEVICES ----
----------------

hl.gesture({
    fingers   = 3,
    direction = "horizontal",
    action    = "workspace",
})

hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exit())
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("/home/igris/.config/scripts/change-layout.sh"))
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd("qs ipc call avatarPicker toggle"))
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("qs ipc call wallhavenPanel toggle"))
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd("qs ipc call powerMenu toggle"))
hl.bind(mainMod .. " + G", hl.dsp.exec_cmd("/home/igris/.local/bin/goland"))
hl.bind(mainMod .. " + K", hl.dsp.exec_cmd("kdeconnect-app"))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("qs ipc call wallpaper toggle"))

-- App launchers (ALT)
hl.bind("ALT + D", hl.dsp.exec_cmd("discord"))
hl.bind("ALT + V", hl.dsp.exec_cmd("prime-run vesktop"))
hl.bind("ALT + M", hl.dsp.exec_cmd("spotify-launcher"))
hl.bind("ALT + G", hl.dsp.exec_cmd("google-chrome-stable"))
hl.bind("ALT + P", hl.dsp.exec_cmd("firefox https://chat.openai.com"))
hl.bind("ALT + T", hl.dsp.exec_cmd("postman"))
hl.bind("ALT + S", hl.dsp.exec_cmd("slack"))
hl.bind("ALT + W", hl.dsp.exec_cmd("/home/igris/.local/bin/webstorm"))
hl.bind("ALT + H", hl.dsp.exec_cmd("quickshell -p ~/.config/quickshell/Lock.qml"))
hl.bind("ALT + F", hl.dsp.exec_cmd("firefox"))
hl.bind("ALT + E", hl.dsp.exec_cmd("ez-fm"))
hl.bind("ALT + C", hl.dsp.exec_cmd("code"))
hl.bind("ALT + SHIFT + G", hl.dsp.group.toggle())
hl.bind("ALT + SHIFT + N", hl.dsp.exec_cmd("qs ipc call networkPanel changeVisible"))
hl.bind("ALT + SHIFT + C", hl.dsp.exec_cmd("qs ipc call controlCenter changeVisible"))
hl.bind("ALT + TAB", hl.dsp.exec_cmd("qs ipc call expose toggle"))

-- Screenshots (Print)
hl.bind("Print",         hl.dsp.exec_cmd([[grimblast save output ~/Pictures/screenshot_$(date +"%Y-%m-%d_%H-%M-%S").png]]))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd([[grimblast save area ~/Pictures/screenshot_$(date +"%Y-%m-%d_%H-%M-%S").png]]))
hl.bind("CTRL + Print",  hl.dsp.exec_cmd("grimblast copy area"))

-- Screen recording (wf-recorder)
hl.bind("ALT + R", hl.dsp.exec_cmd([[wf-recorder -o $(hyprctl -j activeworkspace | jq -r '.monitor') -f "/home/igris/recordings/record_$(date +%Y-%m-%d_%H-%M-%S).mp4" &]]))
-- NOTE: original was `exec, [kill -SIGINT wf-recorder` (malformed). Fixed to pkill.
hl.bind("ALT + SHIFT + R", hl.dsp.exec_cmd("pkill -SIGINT -x wf-recorder"))

-- Fullscreen
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen" }))

-- Scrolling layout messages
hl.bind(mainMod .. " + period",  hl.dsp.layout("move +col"))
hl.bind(mainMod .. " + comma",   hl.dsp.layout("swapcol l"))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.layout("colresize -.25"))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Switch to / move window to workspaces [1-0]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Special workspace (scratchpad). Both binds must reference the SAME special
-- workspace: toggle "magic" <-> move to "special:magic".
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Volume + brightness (locked = works on lockscreen, repeating = repeat when held)
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"),  { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),  { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl set +5%"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), { locked = true, repeating = true })

-- Media keys (playerctl)
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

hl.window_rule({
    name           = "suppress-maximize-events",
    match          = { class = ".*" },
    suppress_event = "maximize",
})

hl.window_rule({
    name      = "slack-ws2",
    match     = { class = "^(Slack)$" },
    workspace = "2",
    opacity   = "1 1",
})

hl.window_rule({
    name      = "spotify-ws3",
    match     = { class = "^(spotify)$" },
    workspace = "3",
    opacity   = "0.75 0.75",
})

hl.window_rule({
    name      = "discord-ws4",
    match     = { class = "^(discord)$" },
    workspace = "4",
    opacity   = "1 1",
})

hl.window_rule({
    name    = "chrome-opacity",
    match   = { class = "^(Google-chrome)$" },
    opacity = "0.85 0.85",
})

hl.window_rule({
    name    = "blueman-opacity",
    match   = { class = "^(blueman-manager)$" },
    opacity = "0.9 0.9",
})
